extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - next/core-web-vitals
    - prettier
ignorePatterns:
    - "**/*.config.js"
    - "**/*.config.mjs"
    - "**/*.config.ts"
parser: "@typescript-eslint/parser"
parserOptions:
    project: "./tsconfig.json"
plugins:
    - "@typescript-eslint"
root: true
rules:
    "@typescript-eslint/consistent-type-definitions":
        - error
        - type
    import/order:
        - warn
        - groups:
              - builtin
              - external
              - type
              - parent
              - sibling
              - internal
              - index
              - object
          pathGroups:
              - pattern: "@/**"
                group: internal
          alphabetize:
              order: asc
